chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('user_id=<int:user_id>', views.user_all_chats, name='user-chats'),
    path('user_id=<int:user_id>/chat_id=<int:chat_id>', views.user_chat, name='user-chat'),
]

jobseeker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include("main.urls")),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('chats/', include('chat.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path('login_user', views.login_user, name='login'),
    path('logout_user', views.logout_user, name='logout'),
    path('register_user', views.register_user, name='registration'),
    path('<int:pk>', views.user_detail, name='user-detail'),
    path('hr/<int:pk>', views.hr_detail, name='hr-detail')
]

main/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.postgres.fields import IntegerRangeField, DecimalRangeField
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Country(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Countries"


class Company(models.Model):
    name = models.CharField(max_length=100)
    employees = IntegerRangeField()
    contact_info = models.CharField(max_length=200)
    description = models.TextField()

    class Meta:
        verbose_name_plural = "Companies"

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    first_name = models.CharField(max_length=32, null=True)
    last_name = models.CharField(max_length=32, null=True)
    expected_salary_range = IntegerRangeField(null=True)
    experience = models.DecimalField(max_digits=3, decimal_places=1, null=True)
    profile_picture = models.ImageField(upload_to='pfp/', null=True)
    resume = models.FileField(upload_to='cv/', blank=True, null=True)
    contact_info = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.user.email


class HR(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    is_hr = models.BooleanField(default=True)
    first_name = models.CharField(max_length=32, null=True)
    last_name = models.CharField(max_length=32, null=True)
    profile_picture = models.ImageField(null=True)
    contact_info = models.CharField(max_length=200, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.user.email


class Vacancy(models.Model):
    WORK_STATUS_CHOICES = [
        ('fulltime', 'Полный рабочий день'),
        ('part-time', 'Частичная занятость'),
        ('remote', 'Удалённая работа'),
    ]

    ENGLISH_LEVEL_CHOICES = [
        ('B1', 'Intermediate'),
        ('B2', 'Upper-Intermediate'),
        ('C1', 'Advanced')
    ]

    title = models.CharField(max_length=100)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    salary_range = IntegerRangeField()
    required_experience_range = DecimalRangeField()
    description = models.TextField()
    responsibilities = models.TextField()
    requirements = models.TextField()
    benefits = models.TextField()
    country = models.ForeignKey(Country, on_delete=models.PROTECT, blank=True)
    work_status = models.CharField(max_length=32, choices=WORK_STATUS_CHOICES, default='fulltime')
    views = models.ManyToManyField(UserProfile, related_name='viewed_vacancies')
    responses = models.ManyToManyField(UserProfile, related_name='responded_vacancies')
    english_level = models.CharField(max_length=32, choices=ENGLISH_LEVEL_CHOICES, default='B2')
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)
    publisher = models.ForeignKey(HR, on_delete=models.PROTECT, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Vacancies"

    def __str__(self):
        return f"{self.title} at {self.company}"


class Response(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Ожидает рассмотрения'),
        ('accepted', 'Принят'),
        ('rejected', 'Отклонён'),
    ]
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

users/forms.py
from django import forms
from main.models import UserProfile, HR


class UserProfileChangeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control', 'style': 'width: 50%;'})

    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name', 'expected_salary_range', 'experience', 'contact_info', 'resume')


class UserProfilePictureChangeForm(forms.ModelForm):
    profile_picture = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))

    class Meta:
        model = UserProfile
        fields = ("profile_picture",)


class HRProfileChangeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control', 'style': 'width: 50%;'})

    class Meta:
        model = HR
        fields = ('first_name', 'last_name', 'contact_info', 'company')


class HRProfilePictureChangeForm(forms.ModelForm):
    profile_picture = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))

    class Meta:
        model = HR
        fields = ("profile_picture",)

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from main.forms import CustomUserCreationForm
from main.models import UserProfile, HR, Vacancy
from .forms import UserProfileChangeForm, HRProfileChangeForm, UserProfilePictureChangeForm, HRProfilePictureChangeForm


def login_user(request):
    if request.method == 'POST':
        email = request.POST["userEmail"]
        password = request.POST["userPassword"]

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('vacancies')
        else:
            messages.success(request, "Введены неверные данные, попробуйте снова!")
            return redirect('login')
    else:
        return render(request, 'users/login.html')


def logout_user(request):
    logout(request)

    messages.success(request, "Вы вышли из учётной записи.")
    return redirect('vacancies')


def register_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']

            user = authenticate(email=email, password=password)
            login(request, user)

            if form.cleaned_data['is_hr'] is True:
                new_hr = HR.objects.create(user=user, is_hr=True)
                new_hr.save()

                messages.success(request, "Аккаунт нанимателя создан.")
            else:
                new_user = UserProfile.objects.create(user=user)
                new_user.save()
                messages.success(request, "Аккаунт создан.")

            messages.success(request, "Регистрация прошла успешно!")

            return redirect('vacancies')
    else:
        form = CustomUserCreationForm()

    return render(request, 'users/registration.html', {"registration_form": form})


@login_required
def user_detail(request, pk):
    user_profile = UserProfile.objects.get(user__pk=pk)

    if request.method == 'POST':
        user_form = UserProfileChangeForm(request.POST, request.FILES, instance=user_profile)
        pfp_form = UserProfilePictureChangeForm(request.POST, request.FILES, instance=user_profile)

        if user_form.is_valid():
            user_form.save()

        if pfp_form.is_valid():
            pfp_form.save()

            messages.success(request, "Информация о профиле была изменена.")
        else:
            messages.success(request, "Не удалось изменить информацию о профиле.")

    else:
        user_form = UserProfileChangeForm(instance=user_profile)
        pfp_form = UserProfilePictureChangeForm(instance=user_profile)

    return render(request, 'users/user_detail.html', {'form': user_form, 'pfp_form': pfp_form})


@login_required
def hr_detail(request, pk):
    hr_profile = HR.objects.get(user__pk=pk)

    hr_vacancies = Vacancy.objects.filter(publisher=hr_profile)

    if request.method == 'POST':
        form = HRProfileChangeForm(request.POST, request.FILES, instance=hr_profile)
        pfp_form = HRProfilePictureChangeForm(request.POST, request.FILES, instance=hr_profile)

        if form.is_valid():
            form.save()

        if pfp_form.is_valid():
            pfp_form.save()

            messages.success(request, "Информация о профиле была изменена.")
        else:
            messages.success(request, "Не удалось изменить информацию о профиле.")

    else:
        form = HRProfileChangeForm(instance=hr_profile)
        pfp_form = HRProfilePictureChangeForm(instance=hr_profile)

    return render(request, 'users/hr_detail.html', {'form': form, "pfp_form": pfp_form, "hr_vacancies": hr_vacancies})

templates/users/hr_detail.html
{% extends "main/base.html" %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'users/user_detail.css' %}">
{% endblock %}

{% block body %}
    <div class="container user-page">
        <div class="row">
            <div class="col-lg-10">
                <div class="page-header">
                    <h1>Мой аккаунт</h1>
                    <div class="page-header-links">
                        <a href="#" onclick="showProfileInfoForm(event)">Информация о профиле</a>
                        <a href="#" onclick="showAvatarImage(event)">Аватар</a>
                        <a href="#" onclick="showPostedVacancies(event)">Опубликованные вакансии</a>
                    </div>
                    <hr style="background-color: white" >
                </div>

                <div class="page-midpart" id="profile-info-form">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="id_first_name" class="col-sm-2 col-form-label">Имя:</label>
                            <div class="col-sm-10">
                                {{ form.first_name }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="id_last_name" class="col-sm-2 col-form-label">Фамилия:</label>
                            <div class="col-sm-10">
                                {{ form.last_name }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="id_first_name" class="col-sm-2 col-form-label">Контакты:</label>
                            <div class="col-sm-10">
                                {{ form.contact_info }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="id_first_name" class="col-sm-2 col-form-label">Компания:</label>
                            <div class="col-sm-10">
                                {{ form.company }}
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </form>
                </div>

                <div class="page-midpart pfp-div" id="profile-picture-form" style="display: none;">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-sm-10">
                                {% if pfp_form.instance.profile_picture %}
                                    <img src="{{ pfp_form.instance.profile_picture.url }}" alt="Profile Picture">
                                {% endif %}
                                {{ pfp_form }}
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </form>
                </div>

                <div class="page-midpart pfp-div" style="display: none;" id="posted-vacancies">
                    {% for vacancy in hr_vacancies %}
                        {{ vacancy }}<br>
                        {% for response in vacancy.responses.all %}
                            {{ response }}
                        {% endfor %}
                    {% endfor %}
                </div>

                <p><a href="{% url 'logout' %}">Выйти из учётной записи</a></p>

                {% if user_errors %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for error in user_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <script>
        function showProfileInfoForm(event) {
            event.preventDefault();
            document.getElementById("profile-info-form").style.display = "block";
            document.getElementById("profile-picture-form").style.display = "none";
            document.getElementById("posted-vacancies").style.display = "none";
        }

        function showAvatarImage(event) {
            event.preventDefault();
            document.getElementById("profile-info-form").style.display = "none";
            document.getElementById("profile-picture-form").style.display = "block";
            document.getElementById("posted-vacancies").style.display = "none";
        }

        function showPostedVacancies(event) {
            event.preventDefault();
            document.getElementById("profile-info-form").style.display = "none";
            document.getElementById("profile-picture-form").style.display = "none";
            document.getElementById("posted-vacancies").style.display = "block";
        }
    </script>
{% endblock %}

templates/users/login.html
{% extends "main/base.html" %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'users/login.css' %}">
{% endblock %}

{% block body %}
    <div class="shadow-lg p-4 mb-5 bg-body rounded" style="margin: 50px;">
        <h3>Вход</h3>
        <form action="" method="POST">
        {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" name="userEmail" aria-describedby="emailHelp" placeholder="Enter email">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" name="userPassword" placeholder="Password">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

        <a href="{% url 'registration' %}" style="margin-top: 10px;"><p>Вы ещё не зарегистрированы?</p></a>
    </div>
{% endblock %}

templates/users/registration.html
{% extends "main/base.html" %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'users/registration.css' %}">
{% endblock %}

{% block body %}
<div class="shadow-lg p-4 mb-5 bg-body rounded" style="margin: 50px;">
        <h3>Регистрация</h3>

        {% if registration_form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                Ошибка при попытке регистрации, попробуйте ещё раз.
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        {% endif %}

        <form action="{% url 'registration' %}" method="POST">
            {% csrf_token %}
            {{ registration_form.as_p }}

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

templates/users/user_detail.html
{% extends "main/base.html" %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'users/user_detail.css' %}">
{% endblock %}

{% block body %}
    <div class="container user-page">
        <div class="row">
            <div class="col-lg-10">
                <div class="page-header">
                    <h1>Мой аккаунт</h1>
                    <div class="page-header-links">
                        <a href="#" onclick="showProfileInfoForm(event)">Информация о профиле</a>
                        <a href="#" onclick="showAvatarImage(event)">Аватар</a>
                    </div>
                    <hr style="background-color: white" >
                </div>

                <div class="page-midpart" id="profile-info-form">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="id_first_name" class="col-sm-2 col-form-label">Имя:</label>
                            <div class="col-sm-10">
                                {{ form.first_name }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="id_last_name" class="col-sm-2 col-form-label">Фамилия:</label>
                            <div class="col-sm-10">
                                {{ form.last_name }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="id_last_name" class="col-sm-2 col-form-label">Ожидаемая зарплата: </label>
                            <div class="col-sm-10">
                                {{ form.expected_salary_range }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="id_last_name" class="col-sm-2 col-form-label">Опыт:</label>
                            <div class="col-sm-10">
                                {{ form.experience }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="id_last_name" class="col-sm-2 col-form-label">Контакты:</label>
                            <div class="col-sm-10">
                                {{ form.contact_info }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="id_last_name" class="col-sm-2 col-form-label">Резюме:</label>
                            <div class="col-sm-10">
                                {{ form.resume }}
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </form>
                </div>

                <div class="page-midpart pfp-div" id="profile-picture-form" style="display: none;">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-sm-10">
                                {% if pfp_form.instance.profile_pifture %}
                                    <img src="{{ pfp_form.instance.profile_picture.url }}" alt="Profile Picture">
                                {% endif %}
                                {{ pfp_form }}
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </form>
                </div>

                <p><a href="{% url 'logout' %}">Выйти из учётной записи</a></p>

                {% if user_errors %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for error in user_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

<script>
    function showProfileInfoForm(event) {
        event.preventDefault();
        document.getElementById("profile-info-form").style.display = "block";
        document.getElementById("profile-picture-form").style.display = "none";
    }

    function showAvatarImage(event) {
        event.preventDefault();
        document.getElementById("profile-info-form").style.display = "none";
        document.getElementById("profile-picture-form").style.display = "block";
    }
</script>
{% endblock %}